external_labels:
  monitor: 'codelab-monitor'
  scrape_configs:
    - job_name: 'nomad'
      scrape_interval: 5s
      metrics_path: /v1/metrics
      params:
       format: ['prometheus']
      static_configs:
        - targets: ['localhost:4646']
